config {
    type: "table",
    schema: "initialization",
    name: "INT_SALES_ADVISOR",
    tags: ["dimensions", "initialization","sales_advisor"]
}
js {
  const env_prefix = dataform.projectConfig.vars.env === "dev" ? "dev" :
                     dataform.projectConfig.vars.env === "ppd" ? "ppd" :
                     "prd";
} 

SELECT 
sales_person_key,
store_code,
last_name,
first_name,
email,
telephone,
sales_person_position
 FROM mja_us_bqd_dpf_y2_01_${env_prefix}.Y2_SALES_ASSOCIATES
